- name: Test Linux system optimization
  hosts: "mongo_master, mongo_replicas"
  become: yes
  gather_facts: yes
  pre_tasks: 
    - name: install the latest version of java-1.8
      yum: name=java-1.8.0-openjdk state=latest
    - name: correct java version selected
      alternatives: name=java link=/usr/bin/java path=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.101-3.b13.24.amzn1.x86_64/jre/bin/java

  roles:
    - ansible-mongodb-optimize
  vars:
        mongodb_security_authorization: "enabled"
        mongodb_conf_auth: true
        mongodb_version: "3.2"
        mongodb_pymongo_pip_version: "3.3"
        mongodb_user: mongod
        mongodb_package: mongodb-enterprise
        mongodb_pymongo_from_pip: true
        mongodb_daemon_name: mongod
        mongodb_replication_replset: mongo-rs
        mongodb_net_maxconns: 51200
        mongodb_processmanagement_fork: true 
        mongodb_systemlog_path: "/var/log/mongodb/mongod.log"
#        mongodb_conf_auth: true
#        mongodb_conf_replSet: false
#        mongodb_conf_bind_ip: '{{ ansible_eth0["ipv4"]["address"] }},127.0.0.1' 
#        mongodb_net_bindip: '{{ ansible_eth0["ipv4"]["address"] }}'
        mongodb_net_bindip: 0.0.0.0
         
        mongodb_users:
          - {
            name: testUser,
            password: passw0rd,
            roles: readWrite,
            database: app_development
         }
# mongodb_replication_params should be configured on each replica set node
        mongodb_login_host: "{{ hostvars[groups['mongo_master'][0]]['ansible_eth0']['ipv4']['address'] }}"
        mongodb_replication_params:
          - { host_name: "{{ hostvars[groups['mongo_master'][0]]['ansible_eth0']['ipv4']['address'] }}", host_port: "{{ mongodb_net_port }}", host_type: replica }
          - { host_name: "{{ hostvars[groups['mongo_replicas'][0]]['ansible_eth0']['ipv4']['address'] }}", host_port: "{{ mongodb_net_port }}", host_type: replica }
          - { host_name: "{{ hostvars[groups['mongo_replicas'][1]]['ansible_eth0']['ipv4']['address'] }}", host_port: "{{ mongodb_net_port }}", host_type: replica }
#     # host_type can be replica(default) and arbiter
#
