- name: mongodb
  hosts: "{{ cluster_name }}_mongo"
  become: yes
  gather_facts: yes
  pre_tasks:
    - name: install the latest version of java-1.8
      yum: name=java-1.8.0-openjdk state=latest
    - name: correct java version selected
      alternatives: name=java link=/usr/bin/java path=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.101-3.b13.24.amzn1.x86_64/jre/bin/java

  roles:
    - ansible-mongodb
  vars:
        mongodb_version: "3.2"
        mongodb_replication_replset: mongo-rs
        mongodb_processmanagement_fork: true
        mongodb_users:
          - {
            name: testUser,
            password: passw0rd,
            roles: readWrite,
            database: app_development
         }

      # mongodb_replication_params should be configured on each replica set node
      # host_type can be replica(default) and arbiter
#        mongodb_replication_params: |
#          {% for host in groups['icemongo_mongo'] %}
#            - { hostname: "{{ hostvars[host]['ansible_eth0']['ipv4']['address'] }}", host_port: "{{ mongodb_net_port }}", host_type: replica }
#          {% endfor %}

        mongodb_replication_params: |
          {% set comma = joiner(',') %}
          {% for host in groups['icemongo_mongo'] -%}
            {{ comma() }}{{ hostvars[host].ansible_default_ipv4.address}}
          {%- endfor -%}

      # mongodb_login_host: "{{ mongodb_replication_params[0]['hostname'] }}"

        mongodb_replication_params2:
          - { host_name: "{{ hostvars[groups['icemongo_mongo'][0]]['ansible_eth0']['ipv4']['address'] }}", host_port: "{{ mongodb_net_port }}", host_type: replica }
          - { host_name: "{{ hostvars[groups['icemongo_mongo'][1]]['ansible_eth0']['ipv4']['address'] }}", host_port: "{{ mongodb_net_port }}", host_type: replica }
          - { host_name: "{{ hostvars[groups['icemongo_mongo'][2]]['ansible_eth0']['ipv4']['address'] }}", host_port: "{{ mongodb_net_port }}", host_type: replica }

