- name: mongodb
  hosts: "{{ cluster_name }}_mongo"
  become: yes
  gather_facts: yes
  pre_tasks:
    - name: install the latest version of java-1.8
      yum: name=java-1.8.0-openjdk state=latest
    - name: correct java version selected
      alternatives: name=java link=/usr/bin/java path=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.101-3.b13.24.amzn1.x86_64/jre/bin/java

  roles:
    - ansible-mongodb
  vars:
        mongodb_version: "3.2"
        mongodb_replication_replset: mongo-rs
        mongodb_processmanagement_fork: true
        mongodb_users:
          - {
            name: testUser,
            password: passw0rd,
            roles: readWrite,
            database: app_development
         }

        mongodb_replication_params: "{{ groups['icemongo_mongo']|map('extract', hostvars, ['ansible_eth0','ipv4', 'address']) |list }}" 
      # mongodb_replication_params collect list of hosts, additional params (e.g. host_port, host_type) are defined from variables in hosts file

        mongodb_login_host: "{{ mongodb_replication_params[0] }}"
